name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:

env:
  DIRECTORY: backend

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup backend
        uses: ./.github/actions/setup
        with:
          directory: ${{ env.DIRECTORY }}

      - name: Run unit tests
        working-directory: ${{ env.DIRECTORY }}
        shell: bash
        run: uv run pytest -m "unit" --maxfail=1 --disable-warnings

      - name: Run integration tests
        working-directory: ${{ env.DIRECTORY }}
        shell: bash
        run: uv run pytest -m "integration" --maxfail=1 --disable-warnings
