name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Setup backend
        uses: ./.github/actions/setup
        with:
          directory: backend

      - name: Run unit tests
        working-directory: backend
        run: uv run pytest -m "unit" --maxfail=1 --disable-warnings

      - name: Run integration tests
        working-directory: backend
        run: uv run pytest -m "integration" --maxfail=1 --disable-warnings
