name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/**'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/**'

env:
  DIRECTORY: frontend

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup frontend
        uses: ./.github/actions/setup
        with:
          directory: ${{ env.DIRECTORY }}

      - name: Run unit tests
        uses: ./.github/actions/pytest
        with:
          directory: ${{ env.DIRECTORY }}
          test_type: unit

      - name: Run integration tests
        uses: ./.github/actions/pytest
        with:
          directory: ${{ env.DIRECTORY }}
          test_type: integration

      - name: Report coverage to OctoCov
        uses: k1LoW/octocov-action@v1
        with:
          work-dir: ${{ env.DIRECTORY }}
        continue-on-error: true

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Setup frontend
        uses: ./.github/actions/setup
        with:
          directory: ${{ env.DIRECTORY }}

      - name: Run ruff check
        run: cd ${{ env.DIRECTORY }} && uv run ruff check --output-format github
      # - name: Run pyright
      #   run: uv run pyright

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup frontend
        uses: ./.github/actions/setup
        with:
          directory: ${{ env.DIRECTORY }}

      - name: Run ruff format
        run: cd ${{ env.DIRECTORY }} && uv run ruff format --diff