name: Frontend Tests

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/**'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/**'

env:
  DIRECTORY: frontend

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_types: [unit, integration]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup frontend
        uses: ./.github/actions/setup
        with:
          directory: ${{ env.DIRECTORY }}

      - name: Run ${{ matrix.test_types }} tests
        uses: ./.github/actions/pytest
        with:
          directory: ${{ env.DIRECTORY }}
          test_type: ${{ matrix.test_types }}
